### ISSUE TITLE
'index.js' could not be saved. Error: undefined

### ISSUE THREAD

**Issue by patskid315** [atom/ide-java#126]
1. Go to Atom
2. Click save
3. No save

It was working perfectly 3 hours before. I had no idea what changed. I legit just kept pushing changes to my file. 

I expect it to push to firebase. 

I get error 'index.js' could not be saved.
Error: undefined

Every time I save. 

I am runing on the latest version of mac, firebase and atom.  I have no idea what changes were caused that made it start doing this. I added one var that was supposed to give firebase access to this directory, then was getting the error.

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

---

But this looks like an individual issue, maybe caused by the OS or permissions, I have the same setup and I couldn't reproduce this, if the issue is still persisting feel to open a new issue with the provided template and share as much information to try reproducing the bug
