### ISSUE TITLE
Eclipse JDT warning: Classpath is incomplete

### ISSUE THREAD

**Issue by jeusdi** [atom/ide-java#98]
I'm getting this message when atom is just kicked off:

![image](https://user-images.githubusercontent.com/941639/51705530-2c8b2380-201c-11e9-9966-8969906cfc09.png)

Installed packages:

![image](https://user-images.githubusercontent.com/941639/51705739-b0451000-201c-11e9-84ce-21c5c7bb30a4.png)

Current configuration:

![image](https://user-images.githubusercontent.com/941639/51705799-e1bddb80-201c-11e9-93ac-779796567b13.png)

Any ideas?

**Comment by time1015** [comment]
I stumbled on this problem as well as of time writing this. The wiki page didn't really help all that much since I have my `build.gradle` on the root directory of my project; I was also utilizing a single project, so this shouldn't be a problem for me, but unfortunately it has.

I did a hack into the `main.js` in the `ide-java` package located in my `.atom` directory, and updated the link of the JDT Language Server archive `ide-java` is using (as of version `0.8.3`) to link to the latest version available (`ide-java` has JDT Language Server version `0.14.0`; the latest version for JDT Language Server is `0.32.0`), and it worked for me.

**Comment by Aerijo** [comment]
@time1015 could you make a PR for that update? It sounds like there’s been room for a lot of bug fixes and enhancements upstream.

**Comment by fmusayev** [comment]
same problem

**Comment by 50Wliu** [comment]
Looks like this has been fixed, now that we're on 0.39.0.
